dist: xenial
addons:
  apt:
    packages:
      - libboost-test-dev
language: cpp
compiler:
  - clang
  - gcc
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - bash deploy.sh
  on:
    all_branches: true